- name: variables from files
  hosts: localhost #managing the ansible server itself
  vars_files:
    - variables.yml
  tasks: 
  - name: printing varaibles
    ansible.builtin.debug: 
      msg: "im learning {{COURSE}}, duration is {{DURATION}}"