- name: variables from command line
  hosts: localhost
  tasks: 
  - name: printing varibles from command line
    ansible.builtin.debug: 
      msg: "hii, this is variable from command line name is: {{NAME}}"


  #ansible-playbook -i inventory -e absible_user=centos -e ansible_password=DevOps321 -e NAME=kots 08.vars-args.yaml