- name: create user
  hosts: localhost
  tasks: 
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop 
    register: out 
    ignore_erros: true
  - name: print the command output 
    ansible.builtin.debug: 
      mag: "{{out}}"
  - name: print exit status
    ansible.builtin.debug: 
      msg: "{{out.rc}}"
  - when: out.rc != 0
    name: create user
    ansible.builtin.user: 
      name: roboshop    