- name: Create User
  hosts: localhost
  tasks:
    - name: Check if roboshop user exists
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - name: Print the command output
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Print exit status
      ansible.builtin.debug:
        msg: "{{ out.rc }}"

    - name: Create user
      become: yes
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0
