- name: Create User
  hosts: localhost
  vars_prompt: 
  - name: USER
    prompt: Enter USER TO CREATE
    private: false
  tasks:
    - name: Check if {{USER}} user exists
      ansible.builtin.command: id {{USER}}
      register: out
      ignore_errors: true

    - name: Print the command output
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Print exit status
      ansible.builtin.debug:
        msg: "{{ out.rc }}"

    - name: Create user
      become: yes
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0
