- name: install packages with loop
  hosts: localhost
  become: yes
  tasks: 
  - name: Install package
    ansible.builitin.yum: 
      name: "{{item}}"
      state: installed
    loop: 
      - nginx
      - postfix
      - mailx